### ISSUE TITLE
Consider using koa@2 instead of koa@latest

### ISSUE THREAD

**Issue by detrohutt** [nuxt/koa#1]
As stated on the [Koa Readme](https://github.com/koajs/koa#koa-v2), Once Node supports native async/await Koa will be switching the `latest` tag to point to Koa 2. There is already an [RC](https://nodejs.org/download/rc/v7.6.0-rc.1/) out for Node 7.6.0 ([discussed here](https://github.com/nodejs/node/pull/11185)), which brings async/await support. Would you consider switching this template to Koa 2 or creating another template for Koa 2?

Note: if you decide to keep using Koa 1, you'll probably want to change your version to something like "^1.2.5" so it doesn't break when Koa 2 is "released".

**Comment by Atinux** [comment]
@alexchopin

**Comment by detrohutt** [comment]
I decided to tackle this myself. I made a PR if you're interested in using it. If not that's ok too. :)
