### ISSUE TITLE
Airbnb style support

### ISSUE THREAD

**Issue by detrohutt** [nuxt/koa#4]
I prefer airbnb over Standard style.. I'm considering adding optional support for airbnb to my fork. Is that something you guys would be interested in?

One foreseeable downside is that it could clutter up the template files with handlebars, but I could keep it to a minimum by making a {{abnb}} helper that returns a ';' if airbnb was chosen.

I would also edit the .eslintrc appropriately and make sure all linting passed as part of the feature.

Let me know if this is something you think you guys would use.

**Comment by alexchopin** [comment]
Hi,
I created this template as a response on how use Nuxt with Koa but I don't use so much the template, so any help is more than welcome!
So I could only agree with your suggestions 👍

**Comment by detrohutt** [comment]
Ok, so I'm working on this now and a question has come up. What version of Node would you like to target with this? Is Node v4.x good enough or are you trying to support older versions than that? The airbnb style is more strict and requires use of let/const everywhere among other things. In Node versions < v4.x I would need to use a --harmony flag to enable let/const.

I can also just disable any specific rules that are troublesome or skip some rules in app.js since other files will be transpiled anyway and Node version won't matter. Just not sure which direction to go with it since I'm not sure what versions you'd like to target.
