### ISSUE TITLE
Document how to also make Koa match Nuxt's router.base

### ISSUE THREAD

**Issue by renoirb** [nuxt/koa#46]
Assuming a project needs to have both Nuxt and Koa to answer to non-root routes, it is unclear how we can make Koa *also* support setting a baseUrl to something else than root `/` (e.g. `/foo/`).

# Use case

Ability to support running production build to something else than root `/`.

```js
// nuxt.config.js
module.exports = {
  router: {
    base: '/foo/'
  }
}
```

As documented in [nuxt.js/.../configuration-router](https://nuxtjs.org/api/configuration-router)

# Issue

Koa has no way of knowing the setting change.

# TODO

1. Setup sample repository (see [**renoirb/experiments-nuxt-koa-env-runtime-201806**, branch **rework-hare-20180619**](https://github.com/renoirb/experiments-nuxt-koa-env-runtime-201806/blob/rework-hare-20180619/nuxt.config.js) as a starting point)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c29">#c29</a>)</em></sub></div>

**Comment by renoirb** [comment]
(*tagging Clark Du, for reference*)

Maybe @clarkdo has an idea about this, since **nuxt/koa-template** and **clarkdo/hare** both use Koa alongside Nuxt.

Also, maybe that should be a feature-request, and not be considered a "need help" question.

**Comment by clarkdo** [comment]
Should be a feature request, since we’re going to integrate templates into create-nuxt-app, so could you open a feature request ticket there?

**Comment by renoirb** [comment]
@clarkdo  ✅ done! https://cmty.app/nuxt/create-nuxt-app/issues/c58

**Comment by renoirb** [comment]
@clarkdo  ✅ done! https://cmty.app/nuxt/create-nuxt-app/issues/c58

**Comment by clarkdo** [comment]
Let us monitor in https://github.com/nuxt-community/create-nuxt-app/issues/82
