### ISSUE TITLE
error  in ./server/index.js 

### ISSUE THREAD

**Issue by wen-dong** [nuxt/koa#51]
module build failed: Error: Plugin/Preset files are not allowed to export objects, only function.
 In node_modules\backpack-core\babel.js

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c34">#c34</a>)</em></sub></div>

**Comment by 9yues** [comment]
我也遇到同样的问题了，请问你解决了吗
