### ISSUE TITLE
运行保错

### ISSUE THREAD

**Issue by freecodemans** [nuxt/koa#58]
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (E:\vue\nuxt-learn\node_modules\eslint-loader\index.js:148:18)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c37">#c37</a>)</em></sub></div>

**Comment by freecodemans** [comment]
Sorry, I'm new here

**Comment by 9yues** [comment]
请问你解决这个问题了吗，我也遇到了

**Comment by cnscorpions** [comment]
facing with same issue, any idea to solve it ?

**Comment by cnscorpions** [comment]
@15521054523 not support with latest nuxt version, refers to [compile error with nuxt@2.x #55](https://github.com/nuxt-community/koa-template/issues/55) nuxt版本降一下就行的
