### ISSUE TITLE
Pull request scope preference

### ISSUE THREAD

**Issue by detrohutt** [nuxt/koa#6]
@alexchopin @Atinux While working on the Airbnb style support, I've noticed a small bug I introduced with one of my earlier PRs (app.prod.js fails linting and should be excluded from linting anyway since it's a generated file).

My question is this: In these cases should I make a separate PR to fix each bug I find or just squash into one PR?

In my projects I keep them separate so people can find them more easily and for a easier-to-read history, but I'd like to adhere to whatever your preference for this or nuxt repos in general is.

**Edit:** I should have specified, I'm only talking about **unrelated** bugs I find while working on something else.. I normally squash everything that falls under a single feature/fix.

**Comment by Atinux** [comment]
It's always better to have 1 PR for each feature/bug fix of course 👍
