### ISSUE TITLE
server/index.js - there is circular reference - is it memory leak here?

### ISSUE THREAD

**Issue by Perlover** [nuxt/koa#66]
Hello!

I generated koa template for nuxt and i see there:

```
  app.use((ctx) => {
    ctx.status = 200
    ctx.respond = false // Bypass Koa's built-in response handling
    ctx.req.ctx = ctx // This might be useful later on, e.g. in nuxtServerInit or with nuxt-stash
    nuxt.render(ctx.req, ctx.res)
  })
```

But i think there is circular reference and this is a potential memory leak

I would did by this way:

```
  app.use((ctx) => {
    ctx.status = 200
    ctx.respond = false // Bypass Koa's built-in response handling
    ctx.req.ctx = ctx // This might be useful later on, e.g. in nuxtServerInit or with nuxt-stash
    nuxt.render(ctx.req, ctx.res)
    ctx.req.ctx = null
  })
```

What do you think?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c47">#c47</a>)</em></sub></div>

**Comment by gerasimvol** [comment]
@Perlover I'm facing huge memory leak. your solution helped in dev mode, but not in production. After first API error (i'm using nuxt-axios-module) - koa stops to clean memory

can you contact me? (можно по-русски)
telegram @gerasim_vol
email vol.gerasimenko@gmail.com

**Comment by Perlover** [comment]
My first patch doesn't work - i got req.ctx as `null` inside my `nuxtServerInit`
But today i patched the code as:

```
    app.use( async (ctx) => {
        ctx.status = 200
        ctx.respond = false // Bypass Koa's built-in response handling
        ctx.req.ctx = ctx // This might be useful later on, e.g. in nuxtServerInit or with nuxt-stash
        try {
            await nuxt.render(ctx.req, ctx.res)
        }
        finally {
            setTimeout( () => {ctx.req.ctx = null}, 0)
        }
    })
```

And now i get `req.ctx` object inside into my `nuxtServerInit` (described as `async` or not). I tried `setImmediate` method but i got `req.ctx` as `null`. So i think `nuxtServerInit` to be run anywhere after `async (ctx) => {}` body. But `setTimeout` (low priority loop phase) helped here. @gerasimvol , please to try this and i will please to know any result in production test. Thanks!

**Comment by Perlover** [comment]
@Atinux, can you open this ticket? I think here may be bug because @gerasimvol told to me that after my first patch (first post here) he got a working code without memory leaks but in `dev` mode. I think it's signal that we have memoty leak problem here...

**Comment by Perlover** [comment]
Due to graph GC a circular references not problem for node

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Mark-and-sweep_algorithm

So my patch is not patch
