### ISSUE TITLE
Missing "cross-env NODE_ENV=dev" in "dev" script?

### ISSUE THREAD

**Issue by Camzilla** [nuxt/koa#8]
My app wasn't running in dev-mode so the build wasn't initializing, but fixed by complementing the dev script with "cross-env NODE_ENV=dev". Not sure if it's missing or if the meta.js does something to set it!

BTW great work, nice template! 👍

**Comment by Atinux** [comment]
This is weird, what version of Koa did you choose @Camzilla ?

**Comment by Atinux** [comment]
I just tried with both versions and it works like a charm!

**Comment by Camzilla** [comment]
My bad, ignored the first line of the readme and downloaded project as a zip 🤦‍♀️ installed vue cli and it works like a charm!

Details in: #2
